"""
Chat and Agent Pydantic Schemas.
Defines request and response models for the conversational AI support endpoint.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from app.schemas.session import CustomerContext


class ChatMessageRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000, description="Customer message text")
    conversation_id: Optional[str] = Field(None, description="Optional conversation session ID for multi-turn dialogue")


class ToolExecutionRecord(BaseModel):
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    success: bool = True
    output_preview: Optional[str] = None


class ChatMessageResponse(BaseModel):
    response: str = Field(..., description="Assistant reply generated by the agent")
    intent: Optional[str] = Field(None, description="Classified intent or primary action type")
    tools_executed: List[str] = Field(default_factory=list, description="List of tools invoked during resolution")
    tool_details: List[ToolExecutionRecord] = Field(default_factory=list, description="Details of tool executions")
    customer: Optional[CustomerContext] = Field(None, description="Active customer persona")
    conversation_id: str = Field(..., description="Session conversation ID")
    latency_ms: Optional[float] = Field(None, description="Agent execution latency in milliseconds")


class ChatResetResponse(BaseModel):
    status: str = "success"
    message: str = "Conversation history reset successfully"
    conversation_id: str
